## [Day 11](https://adventofcode.com/2021/day/11): Dumbo Octopus
### Part I
- **Unknown**: The total number of flashes in the grid after 100 steps.
- **Data**: A 10 by 10 grid of octopuses, each with an energy level with a value between 0 and 9.
- **Condition**:
  - The level of octopuses' energy increases in each step by 1.
  - Any octopus with an energy level greater then 9 flashes. This increses the energy level of all adjacent octopuses by 1, including octopuses that are diagonally adjacent.
  - An octopus can only flash at most once per step.
- **Plan**:
  - Parse input into an integer matrix.
  - In each step:
    - Increment the energy level of a matrix by 1.
    - Initialize a list (queue) of positions `to_flash` : `list(zip(*np.asarray(grid>9).nonzero()))`
    - While `to_flash` is not empty:
      - For each neighbour in `set(get_neighbours) - set(to_flash + flashed)`:
        - Increase the energy level by 1
        - If the energy level is grater the 9, add the position to `to_flash`
      - Pop a position from `to_flash` to `flashed`
    - All positions in `flashed` set to 0 and update the sum of flashes.

In [3]:
from pathlib import Path
import numpy as np

In [5]:
def parse(input):
    """Return a grid."""
    grid = Path('data/'+input).read_text().strip()
    grid = np.array([list(line) for line in grid.split('\n')]).astype(int)

    return grid

grid = parse('AoC2021_11ex2.txt')
grid

array([[1, 1, 1, 1, 1],
       [1, 9, 9, 9, 1],
       [1, 9, 1, 9, 1],
       [1, 9, 9, 9, 1],
       [1, 1, 1, 1, 1]])

In [6]:
def get_neighbors(grid, current):
    """Find all the neighbours of a position"""

    x, y = current
    for dx in [-1, 0, 1]:
        for dy in [-1, 0, 1]:
            if not(0 <= x+dx < grid.shape[0] and 0 <= y+dy < grid.shape[1]):
                continue
            elif dx == 0 and dy == 0:
                continue
            else:
                yield (x+dx, y+dy)

list(get_neighbors(grid, (1,0)))

[(0, 0), (0, 1), (1, 1), (2, 0), (2, 1)]

In [7]:
np.asarray(grid>8)

array([[False, False, False, False, False],
       [False,  True,  True,  True, False],
       [False,  True, False,  True, False],
       [False,  True,  True,  True, False],
       [False, False, False, False, False]])

In [8]:
np.asarray(grid>8).nonzero()

(array([1, 1, 1, 2, 2, 3, 3, 3], dtype=int64),
 array([1, 2, 3, 1, 3, 1, 2, 3], dtype=int64))

In [9]:
grid[np.asarray(grid>8).nonzero()]

array([9, 9, 9, 9, 9, 9, 9, 9])

In [11]:
list(zip(*np.asarray(grid>8).nonzero()))

[(1, 1), (1, 2), (1, 3), (2, 1), (2, 3), (3, 1), (3, 2), (3, 3)]

### Part II
- **Unknown**: 
- **Data**: 
- **Condition**: 
- **Plan**: 