# [Day 10](https://adventofcode.com/2020/day/10) : Adapter Array
## Part I


In [5]:
# Import dependencies
from pathlib import Path
import numpy as np
from collections import Counter

In [2]:
def parse(test=True):
    filename = './data/AoC20_10t.txt' if test else './data/AoC20_10.txt'
    lines = Path(filename).read_text().split('\n')
    return [int(l) for l in lines]
a0 = parse()
a0

[16, 10, 15, 5, 1, 11, 7, 19, 6, 12, 4]

In [4]:
a1 = np.array(sorted(a0+[max(a0)+3]))
a2 = np.array(sorted([0]+a0))
a1, a2

(array([ 1,  4,  5,  6,  7, 10, 11, 12, 15, 16, 19, 22]),
 array([ 0,  1,  4,  5,  6,  7, 10, 11, 12, 15, 16, 19]))

In [6]:
dif = a1-a2
dif, Counter(dif)

(array([1, 3, 1, 1, 1, 3, 1, 1, 3, 1, 3, 3]), Counter({1: 7, 3: 5}))

In [8]:
def solve_part1(test=True):
    a0 = parse(test)
    a1 = np.array(sorted(a0+[max(a0)+3]))
    a2 = np.array(sorted([0]+a0))
    dif = a1-a2
    c = Counter(dif)
    return c, c[1]*c[3]
solve_part1()

(Counter({1: 22, 3: 10}), 220)

In [9]:
solve_part1(False)

(Counter({1: 69, 3: 24}), 1656)

## Part II
The **unknown** of this part is **the total number of distinct ways you can arrange the adapters** to connect the charging outlet to your device. An input to this part is the difference array. When there is more then one difference of length 1 in a sequence, it is possible to remove at least one adapter from the chain.

The key to solution is to figure out the relation between the length of sequence of 1 and the number of possible removal.

Lenght of sequence|Number of combinations
-|-
1|0
2|2
3|4 ($= 2^{3-1}$)
4|8 ?
5|?

But we can't use [Number of k-combinations for all k](https://en.wikipedia.org/wiki/Combination#Number_of_k-combinations_for_all_k), which is $\sum_{0 \leq k \leq n} \binom{n}{k} = 2^n$ directly, because the gap between adapters can be at most 3.