# [Day 8](https://adventofcode.com/2022/day/8) : Treetop Tree House
## Part I

In [15]:
# Import dependencies
from pathlib import Path
import numpy as np

In [16]:
def parse(test=True):
    filename = './data/AoC22_08t.txt' if test else './data/AoC22_08.txt'
    lines = Path(filename).read_text().split('\n')
    lines = [list(map(int, list(line))) for line in lines]
    return np.array(lines)
parse()

array([[3, 0, 3, 7, 3],
       [2, 5, 5, 1, 2],
       [6, 5, 3, 3, 2],
       [3, 3, 5, 4, 9],
       [3, 5, 3, 9, 0]])

In [18]:
m = parse(False)
m.shape

(99, 99)

In [39]:
def visible(m,r,c):
    dim = len(m)
    return min(m[r,0:c].max(), m[r,c+1:dim].max(), m.T[c,0:r].max(), m.T[c,r+1:dim].max()) < m[r,c]

def solve_part1(test=True):
    m = parse(test)
    dim = len(m)
    cvisible = 4*dim - 4
    for r in range(1,dim-1):
        for c in range(1,dim-1):
            cvisible += visible(m,r,c)
    return cvisible
solve_part1(True)

21

In [40]:
solve_part1(False)

1669

## Part II

In [60]:
r,c = 1,2
dim = len(m)
print(m)
m[r,c]
print(m.T[c,0:r], m[r,0:c], m[r,c+1:dim], m.T[c,r+1:dim])
m.T[c,0:r][::-1], m[r,0:c][::-1], m[r,c+1:dim], m.T[c,r+1:dim]

[[3 0 3 7 3]
 [2 5 5 1 2]
 [6 5 3 3 2]
 [3 3 5 4 9]
 [3 5 3 9 0]]
[3] [2 5] [1 2] [3 5 3]


(array([3]), array([5, 2]), array([1, 2]), array([3, 5, 3]))

In [64]:
def view(t,d):
    v = 0
    for i in range(len(d)):
        if d[i] >= t:
            v += 1
            break
        else:
            v += 1
    return v
for d in [m.T[c,0:r][::-1], m[r,0:c][::-1], m[r,c+1:dim], m.T[c,r+1:dim]]:
    print(view(m[r,c],d))


1
1
2
2


In [68]:
def solve_part2(test=True):
    m = parse(test)
    dim = len(m)
    highest = 0
    for r in range(1,dim-1):
        for c in range(1,dim-1):
            h = m[r,c]
            scene = view(h,m.T[c,0:r][::-1]) * view(h,m[r,0:c][::-1]) * view(h,m[r,c+1:dim]) * view(h, m.T[c,r+1:dim])
            #print(h, scene)
            if scene > highest:
                highest = scene
    return highest
solve_part2(True)

    

8

In [69]:
solve_part2(False)

331344